console.log("This is conflige system")
console.log("every thing is hefo the super star !!")
console.log("every thing is something!!")
console.log("every thing is slfksl!!")
console.log("every thing is sfsfsfsfsfsf!!")