console.log("This is conflige system")
console.log("every thing is bad!!")
console.log("every thing is something!!")
console.log("every thing is slfksl!!")
console.log("every thing is sfsfsfsfsfsf!!")